---
name: debug_context
#yamllint disable

on:
  workflow_dispatch:

run-name: ${{ github.ref_name }} -> debug_context (
  ${{ github.run_attempt }}
  )
    
jobs:

  debug_context:
    
    name: debug_context
    runs-on: ubuntu-latest
    steps:
      - name: Echo current date and time
        id: datetime
        run: |
          echo "datetime: $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"