---
name: deploy_to_cloudflare
# yamllint disable rule:line-length

on:
  release:
    types: [released]
  workflow_dispatch:


# set the run-name 
run-name: ${{ github.ref_name }} -> deploy_to_cloudflare (
  ${{ github.run_attempt }}
  )


jobs:
  deploy_to_cloudflare:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: deploy_to_cloudflare
    steps:
      - name: Echo current date and time
        id: datetime
        run: |
          echo "datetime: $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Checkout
        uses: actions/checkout@v3.6.0

      # Run a build step here if your project requires

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUFLARE_EDIT_PAGES_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: www-intellireading
          directory: src
          branch: main
          # Optional: Change the Wrangler version, allows you to point to 
          # a specific version or a tag such as `beta`
          wranglerVersion: '3'