---
name: super_linter

on:
  release:
    types: [released]
  pull_request:
    branches: [master, main]

  workflow_dispatch:
  
  schedule:
    # run on mondays and thursdays at 00:00 UTC
    - cron: '0 0 * * 1'
    
# set the run-name 
run-name: ${{ github.ref_name }} -> super_linter (
  ${{ github.run_attempt }}
  )

permissions: read-all

jobs:
  super_linter:

    name: super_linter
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      statuses: write

    steps:

      - name: Echo current date and time
        id: datetime
        run: |
          echo "datetime: $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
